version: "3.8"

services:
  web:
    build:
      context: .
    env_file:
      .env.docker
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis_db:
        condition: service_started
    restart: always

  db:
    image: postgres:latest
    env_file:
      .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_db:
    image: redis:latest
    restart: always
    volumes:
      - data:/var/lib/redis

volumes:
  postgres_data:
  data:
