"""empty message

Revision ID: e033cbc5138e
Revises: 8ecad2e63aba
Create Date: 2023-07-02 06:26:58.087632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e033cbc5138e'
down_revision = '8ecad2e63aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_title', table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    # ### end Alembic commands ###
